# Generated by Django 4.2 on 2026-05-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item_list', '0002_category_subtype_type_alter_item_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='es_fabricable',
            field=models.BooleanField(default=False, help_text='Marcar si este item se puede fabricar mediante receta'),
        ),
    ]
