# Generated by Django 4.2 on 2026-08-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe_list', '0002_alter_recipe_recipe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='produces_quantity',
            field=models.PositiveBigIntegerField(default=1, help_text='Cantidad de unidades que se obtienen por lote (ej. 1,2,3...)'),
        ),
    ]
